import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Plain Node build scripts, not app code — the Next/TS browser rules
    // (no-require-imports, browser globals) do not apply to them.
    "scripts/**",
    // Generated from scripts/sw.template.js at prebuild time.
    "public/sw.js",
    // `vercel build` output — bundled artifacts, not source.
    ".vercel/**",
    // Generated by `supabase gen types typescript`; never hand-edited.
    "types/supabase.ts",
  ]),
]);

export default eslintConfig;
